# Generated by Django 5.0.1 on 2024-03-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
